```mermaid
   @startuml Diagramas de Casos de Uso
    left to right direction
    actor "Administrador" as Admin
    actor "Espectador" as Esp

    rectangle "Sistema de Cinema" {
        usecase "Cadastrar Filme/Sessão" as UC1
        usecase "Gerar Relatório de Público" as UC2
        usecase "Consultar Filmes em Cartaz" as UC3
        usecase "Registrar Público da Sessão" as UC4
    }

    Admin --> UC1
    Admin --> UC2
    Admin --> UC4
    Esp --> UC3
    @enduml
```
