@startuml Diagrama de Sequencia
skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Administrador" as Admin #LightBlue
box "Camada de Interface" #Ivory
    participant "view.py\n(CinemaView)" as V
end box

box "Camada de Controle" #LightCyan
    participant "controller.py\n(CinemaController)" as C
end box

box "Camada de Negócio" #LightGoldenRodYellow
    participant "service.py\n(CinemaService)" as S
end box

box "Camada de Dados" #LightPink
    participant "repository.py\n(CinemaRepository)" as R
    database "cinema.db\n(SQLite)" as DB
end box

Admin -> V : Escolhe "Cadastrar Filme"
V -> Admin : Solicita Dados (Título, Duração)
Admin -->> V : Fornece Dados

V -> C : processar_cadastro(titulo, duracao)
C -> S : validar_e_cadastrar_filme(titulo, duracao)

note over S : RN02: Valida se\nduração > 30 min

alt Dados Válidos
    S -> R : salvar_filme(objeto_filme)
    R -> DB : INSERT INTO filmes
    DB -->> R : Confirmar Persistência
    R -->> S : Sucesso
    S -->> C : Mensagem de Confirmação
    C -> V : mostrar_mensagem(sucesso)
    V -> Admin : Exibe "Cadastrar com sucesso"
else Dados Inválidos
    S -->> C : raise ValueError
    C -> V : mostrar_mensagem(erro)
    V -> Admin : Exibe "Erro de Validação"
end

@enduml